package tables;
// Generated 27-ene-2019 20:12:02 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer idcar;
	private String plateNumber;
	private String brand;
	private String model;
	private String color;
	private Set reservations = new HashSet(0);

	public Car() {
	}

	public Car(String plateNumber, String brand, String model, String color, Set reservations) {
		this.plateNumber = plateNumber;
		this.brand = brand;
		this.model = model;
		this.color = color;
		this.reservations = reservations;
	}

	public Integer getIdcar() {
		return this.idcar;
	}

	public void setIdcar(Integer idcar) {
		this.idcar = idcar;
	}

	public String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
