package tables;
// Generated 27-ene-2019 20:12:02 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer idreservation;
	private Client client;
	private Date startDate;
	private Date endDate;
	private Set cars = new HashSet(0);

	public Reservation() {
	}

	public Reservation(Client client) {
		this.client = client;
	}

	public Reservation(Client client, Date startDate, Date endDate, Set cars) {
		this.client = client;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cars = cars;
	}

	public Integer getIdreservation() {
		return this.idreservation;
	}

	public void setIdreservation(Integer idreservation) {
		this.idreservation = idreservation;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set getCars() {
		return this.cars;
	}

	public void setCars(Set cars) {
		this.cars = cars;
	}

	@Override
	public String toString() {
		return "Reservation [idreservation=" + idreservation + ", client=" + client + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", cars=" + cars + "]";
	}
	
}
