package tables;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 21-ene-2019 19:42:27 by Hibernate Tools 4.3.5.Final

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private String plateNumber;
	private String brand;
	private String model;
	private String color;

	public Car() {
	}

	public Car(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public Car(String plateNumber, String brand, String model, String color) {
		this.plateNumber = plateNumber;
		this.brand = brand;
		this.model = model;
		this.color = color;
	}

	public String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
