package tables;
// Generated 21-ene-2019 19:42:27 by Hibernate Tools 4.3.5.Final

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private String dni;
	private String name;
	private String address;
	private String phone;

	public Client() {
	}

	public Client(String dni) {
		this.dni = dni;
	}

	public Client(String dni, String name, String address, String phone) {
		this.dni = dni;
		this.name = name;
		this.address = address;
		this.phone = phone;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
