package tables;
// Generated 21-ene-2019 19:42:27 by Hibernate Tools 4.3.5.Final

/**
 * ReservedcarsId generated by hbm2java
 */
public class ReservedcarsId implements java.io.Serializable {

	private int id;
	private String plateNumber;

	public ReservedcarsId() {
	}

	public ReservedcarsId(int id, String plateNumber) {
		this.id = id;
		this.plateNumber = plateNumber;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservedcarsId))
			return false;
		ReservedcarsId castOther = (ReservedcarsId) other;

		return (this.getId() == castOther.getId()) && ((this.getPlateNumber() == castOther.getPlateNumber())
				|| (this.getPlateNumber() != null && castOther.getPlateNumber() != null
						&& this.getPlateNumber().equals(castOther.getPlateNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getPlateNumber() == null ? 0 : this.getPlateNumber().hashCode());
		return result;
	}

}
