package tables;
// Generated 21-ene-2019 19:42:27 by Hibernate Tools 4.3.5.Final

/**
 * Reservedcars generated by hbm2java
 */
public class Reservedcars implements java.io.Serializable {

	private ReservedcarsId id;

	public Reservedcars() {
	}

	public Reservedcars(ReservedcarsId id) {
		this.id = id;
	}

	public ReservedcarsId getId() {
		return this.id;
	}

	public void setId(ReservedcarsId id) {
		this.id = id;
	}

}
