package tables;
// Generated 21-ene-2019 19:42:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer id;
	private Date startDate;
	private Date endDate;
	private String dni;

	public Reservation() {
	}

	public Reservation(String dni) {
		this.dni = dni;
	}

	public Reservation(Date startDate, Date endDate, String dni) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.dni = dni;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

}
